export default {
  login: 'aljorgevi',
  id: 77608748,
  node_id: 'MDQ6VXNlcjc3NjA4NzQ4',
  avatar_url: 'https://avatars.githubusercontent.com/u/77608748?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/aljorgevi',
  html_url: 'https://github.com/aljorgevi',
  followers_url: 'https://api.github.com/users/aljorgevi/followers',
  following_url:
    'https://api.github.com/users/aljorgevi/following{/other_user}',
  gists_url: 'https://api.github.com/users/aljorgevi/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/aljorgevi/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/aljorgevi/subscriptions',
  organizations_url: 'https://api.github.com/users/aljorgevi/orgs',
  repos_url: 'https://api.github.com/users/aljorgevi/repos',
  events_url: 'https://api.github.com/users/aljorgevi/events{/privacy}',
  received_events_url: 'https://api.github.com/users/aljorgevi/received_events',
  type: 'User',
  site_admin: false,
  name: 'Jorge Andrés Mena',
  company: 'Loki rent a car',
  blog: 'www.aljorgevi.com',
  location: 'London',
  email: null,
  hireable: null,
  bio: ' Business Engineer and JavaScript Developer.',
  twitter_username: 'aljorgevi',
  public_repos: 16,
  public_gists: 0,
  followers: 1,
  following: 9,
  created_at: '2021-01-18T07:49:57Z',
  updated_at: '2021-06-12T08:58:04Z',
};
