export default [
  {
    login: 'mxmnk',
    id: 46030850,
    node_id: 'MDQ6VXNlcjQ2MDMwODUw',
    avatar_url: 'https://avatars.githubusercontent.com/u/46030850?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mxmnk',
    html_url: 'https://github.com/mxmnk',
    followers_url: 'https://api.github.com/users/mxmnk/followers',
    following_url: 'https://api.github.com/users/mxmnk/following{/other_user}',
    gists_url: 'https://api.github.com/users/mxmnk/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mxmnk/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mxmnk/subscriptions',
    organizations_url: 'https://api.github.com/users/mxmnk/orgs',
    repos_url: 'https://api.github.com/users/mxmnk/repos',
    events_url: 'https://api.github.com/users/mxmnk/events{/privacy}',
    received_events_url: 'https://api.github.com/users/mxmnk/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'zendy199x',
    id: 50132805,
    node_id: 'MDQ6VXNlcjUwMTMyODA1',
    avatar_url: 'https://avatars.githubusercontent.com/u/50132805?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/zendy199x',
    html_url: 'https://github.com/zendy199x',
    followers_url: 'https://api.github.com/users/zendy199x/followers',
    following_url:
      'https://api.github.com/users/zendy199x/following{/other_user}',
    gists_url: 'https://api.github.com/users/zendy199x/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/zendy199x/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/zendy199x/subscriptions',
    organizations_url: 'https://api.github.com/users/zendy199x/orgs',
    repos_url: 'https://api.github.com/users/zendy199x/repos',
    events_url: 'https://api.github.com/users/zendy199x/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/zendy199x/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'cochoaguilo',
    id: 70769135,
    node_id: 'MDQ6VXNlcjcwNzY5MTM1',
    avatar_url: 'https://avatars.githubusercontent.com/u/70769135?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/cochoaguilo',
    html_url: 'https://github.com/cochoaguilo',
    followers_url: 'https://api.github.com/users/cochoaguilo/followers',
    following_url:
      'https://api.github.com/users/cochoaguilo/following{/other_user}',
    gists_url: 'https://api.github.com/users/cochoaguilo/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/cochoaguilo/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/cochoaguilo/subscriptions',
    organizations_url: 'https://api.github.com/users/cochoaguilo/orgs',
    repos_url: 'https://api.github.com/users/cochoaguilo/repos',
    events_url: 'https://api.github.com/users/cochoaguilo/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/cochoaguilo/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'hacker8853',
    id: 76920935,
    node_id: 'MDQ6VXNlcjc2OTIwOTM1',
    avatar_url: 'https://avatars.githubusercontent.com/u/76920935?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/hacker8853',
    html_url: 'https://github.com/hacker8853',
    followers_url: 'https://api.github.com/users/hacker8853/followers',
    following_url:
      'https://api.github.com/users/hacker8853/following{/other_user}',
    gists_url: 'https://api.github.com/users/hacker8853/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/hacker8853/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/hacker8853/subscriptions',
    organizations_url: 'https://api.github.com/users/hacker8853/orgs',
    repos_url: 'https://api.github.com/users/hacker8853/repos',
    events_url: 'https://api.github.com/users/hacker8853/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/hacker8853/received_events',
    type: 'User',
    site_admin: false,
  },
];
